In [1]:
import pandas as pd

## Reading in heat pump water heater dataset and preliminary analysis

In [12]:
heatpump_df = pd.read_excel('TECHWorkingDataset_Single-Family_2026-08-17.xlsx')

num_rows = len(heatpump_df)
num_rows

print(heatpump_df.shape)
#this dataset has 67,850 rows and 104 columns

heatpump_df.head()

(67850, 104)

,Project Index,Contractor Index,Project Site Index,Customer City,Customer County,Gas IOU Territory #1,Gas IOU Territory #2,CA Climate Zone,Disadvantaged Community,TECH Equity Community,...,Customer Enrolled in Demand Response Program,TOU Enrollment Rate,Communication Module Add-On,Duct Replacement,Duct Sealing,Smart Thermostat Included,Manual D/J Completed,Previous AC Type,Previous Furnace Fuel Type,Furnace Status After Install
0,1,148.0,3460,Other,Contra Costa County,Pacific Gas & Electric,NaN,12,False,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,19.0,3701,LIVERMORE,Alameda County,Pacific Gas & Electric,NaN,12,False,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,389.0,3703,FAIR OAKS,Sacramento County,Pacific Gas & Electric,NaN,12,False,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,84.0,3776,ROSEVILLE,Placer County,Pacific Gas & Electric,NaN,11,False,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,84.0,3788,FAIR OAKS,Sacramento County,Pacific Gas & Electric,NaN,12,False,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Print all column names to understand dataset

In [13]:
for col in heatpump_df.columns: 
    print(col)

Project Index
Contractor Index
Project Site Index
Customer City
Customer County
Gas IOU Territory #1
Gas IOU Territory #2
CA Climate Zone
Disadvantaged Community
TECH Equity Community
Census Tract Median Household Income ($ thousands)
Building Type
Year Built
Total Living Floor Area (Sq Ft)
Number of Bedrooms
Panel Capacity Pre Install (Amps)
Panel Capacity Post Install (Amps)
Claim ID
Program Name
Program Income Qualification
Product Group
Installed Equipment Description
Material Category
Product Type
Brand Index
Model Production Status
AHRI Type
AHRI Descriptor
HPWH Equipment Type
NEEA Tier
Uniform Energy Factor
Coefficient of Performance (COP)
Rated Storage Volume (gal)
First Hour Rating (GPH)
CTA-2045
Input Rate (kW)
NEEA Cold Climate Efficiency
Recovery Efficiency per UEF test method (percent)
Connected Functionality
CEE Minimum Tier
JA13 Qualified
Refrigerant
Global Warming Potential of Refrigerant
Large Commercial Unit
Usage Bin
HVAC Equipment Type
Ducted
Ducting Type
Compressor Type
Cold Climate Designation
Cooling Source
Cooling Capacity (tons)
Heating Capacity (tons)
EER
SEER
HSPF (Region IV)
EER2
SEER2
HSPF2 (Region IV)
Ex Ante annual electricity savings (kWh)
Ex Ante annual gas/propane savings (Therms)
Ex Ante annual GHG savings (Metric tons CO2e)
Count Units Installed
Total Project Cost ($)
Total Project Cost per Unit ($)
HPWH Norm Cost ($/gal)
HVAC Norm Cost ($/ton)
Equipment Cost ($)
Total Electrical Upgrade Cost Qualifying for Incentive (SGIP HPWH)
Incentive 1 ($)
Incentive 1 Funder
Incentive 2 ($)
Incentive 2 Funder(s)
Total Incentive Received by Contractor ($)
Installation Start Date
Installation End Date
Installation Duration (days)
Permit Request
Electrical Service Upgrade
Electrical Service Upgrade Type
Emergency Replacement
Emergency Backup Type
HPWH Operating Mode
Location HPWH Installed in Bldg
Condensate Pump Required
Mixing Valve Installed
Grid Connected
Previous WH Type
Previous WH Volume (gal)
Previous WH Fuel Type
HPWH Temp Set Point
Previous WH Location
Bedrooms Served
Bathrooms Served
Customer Enrolled in Demand Response Program
TOU Enrollment Rate
Communication Module Add-On
Duct Replacement
Duct Sealing
Smart Thermostat Included
Manual D/J Completed
Previous AC Type
Previous Furnace Fuel Type
Furnace Status After Install

Based on the above list of columns, I think the most interesting ones to keep are: Customer County, Census Tract Median Household Income ($ thousands), Building Type, Year Built, Total Living Floor Area (Sq Ft), Number of Bedroom, Product Type, Installation Start Date, Previous AC type, Previous Furnace Fuel Type

But to first get a sense of how many projects are done in each county, I'll first focus on Customer County, Product Type, and Installation Start Date.

### Preliminary Group-by

In [4]:
heatpump_df[['Customer County', 'Product Type', 'Installation Start Date']].groupby(['Customer County', 'Installation Start Date'])['Product Type'].count()

Customer County  Installation Start Date
Alameda County   2021-07-09 00:00:00        1
                 2021-08-27 00:00:00        1
                 2021-09-22 00:00:00        1
                 2021-10-14 00:00:00        2
                 2021-10-17 00:00:00        1
                                           ..
Yuba County      2024-10-01 00:00:00        1
                 2024-10-31 00:00:00        1
                 2025-01-30 00:00:00        1
                 2025-07-30 00:00:00        1
                 2025-08-14 00:00:00        1
Name: Product Type, Length: 17283, dtype: int64

### Preliminary group by results

Preliminary group-by shows we need to create a new column that separates out just the year of installation

### Creating column for just the years of installation

In [19]:
#create a column for just the years of installation
heatpump_df['Year'] = pd.to_datetime(heatpump_df['Installation Start Date'], errors = 'coerce').dt.year.astype('Int64')
heatpump_df

,Project Index,Contractor Index,Project Site Index,Customer City,Customer County,Gas IOU Territory #1,Gas IOU Territory #2,CA Climate Zone,Disadvantaged Community,TECH Equity Community,...,TOU Enrollment Rate,Communication Module Add-On,Duct Replacement,Duct Sealing,Smart Thermostat Included,Manual D/J Completed,Previous AC Type,Previous Furnace Fuel Type,Furnace Status After Install,Year
0,1,148.0,3460,Other,Contra Costa County,Pacific Gas & Electric,NaN,12,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
1,2,19.0,3701,LIVERMORE,Alameda County,Pacific Gas & Electric,NaN,12,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
2,3,389.0,3703,FAIR OAKS,Sacramento County,Pacific Gas & Electric,NaN,12,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
3,4,84.0,3776,ROSEVILLE,Placer County,Pacific Gas & Electric,NaN,11,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
4,5,84.0,3788,FAIR OAKS,Sacramento County,Pacific Gas & Electric,NaN,12,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67845,67846,773.0,13012,Other,Kern County,Pacific Gas & Electric,NaN,16,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural Gas,NaN,<NA>
67846,67847,773.0,13014,RIDGECREST,Kern County,Pacific Gas & Electric,NaN,14,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural Gas,Fully decommissioned,2022
67847,67848,773.0,13032,RIDGECREST,Kern County,Pacific Gas & Electric,NaN,14,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural Gas,Fully decommissioned,2022
67848,67849,773.0,13040,RIDGECREST,Kern County,Pacific Gas & Electric,NaN,14,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural Gas,Fully decommissioned,2022
67849,67850,656.0,13800,Other,Santa Barbara County,Southern California Gas,NaN,6,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural Gas,Fully decommissioned,2022

### Aggregate dataset on years

In [26]:
heatpump_df[['Customer County', 'Product Type', 'Installation Start Date']].groupby(['Customer County', 'Installation Start Date'])['Product Type'].count()

pd.set_option('display.max_rows', None)
heatpump_df.groupby(['Customer County', 'Year'])['Product Type'].count()

Customer County         Year
Alameda County          2021      43
                        2022     755
                        2023    1050
                        2024    1204
                        2025     517
                        2026      30
Alpine County           2024       1
Amador County           2021       2
                        2022       7
                        2023       3
                        2024       5
                        2025       5
                        2026       1
Butte County            2022     100
                        2023      89
                        2024     119
                        2025      37
                        2026       4
Calaveras County        2021       1
                        2022       3
                        2023       7
                        2024       2
                        2025       8
Colusa County           2022       5
                        2023       1
                        2024       2
Contra Costa County     2021      41
                        2022     445
                        2023     720
                        2024     837
                        2025     278
                        2026      33
Del Norte County        2025      13
                        2026       6
El Dorado County        2022      45
                        2023      44
                        2024     107
                        2025      36
                        2026       3
Fresno County           2021      20
                        2022     335
                        2023     651
                        2024     692
                        2025      86
                        2026       7
Glenn County            2022       2
                        2023       6
                        2024       7
                        2025       2
                        2026       1
Humboldt County         2021       1
                        2022      22
                        2023      12
                        2024      16
                        2025      14
                        2026       2
Imperial County         2022      15
                        2023       6
                        2024       9
                        2025     213
                        2026      24
Kern County             2021       1
                        2022     155
                        2023     286
                        2024     226
                        2025     464
                        2026     179
Kings County            2021       1
                        2022      12
                        2023      27
                        2024      46
                        2025       6
Lake County             2022       2
                        2023       2
                        2024       7
                        2025       3
Lassen County           2024       1
Los Angeles County      2021      41
                        2022    1365
                        2023    1365
                        2024    1343
                        2025    1735
                        2026     547
Madera County           2021       1
                        2022      36
                        2023      41
                        2024      37
                        2025      23
Marin County            2021       8
                        2022     259
                        2023     268
                        2024     394
                        2025     106
                        2026       6
Mariposa County         2022       1
                        2023       1
                        2024       1
                        2025       2
Mendocino County        2021       4
                        2022      45
                        2023      18
                        2024      39
                        2025       8
                        2026       1
Merced County           2022      39
                        2023      32
                        2024      61
                        2025      19
                        2026       4
Monterey County         2021       1
                        2022      30
                        2023     100
                        2024      90
                        2025     122
                        2026       6
Napa County             2021       1
                        2022      71
                        2023      63
                        2024     126
                        2025      27
Nevada County           2022      31
                        2023      23
                        2024      67
                        2025      25
Orange County           2021      47
                        2022     792
                        2023     728
                        2024     890
                        2025     301
                        2026      79
Placer County           2021       2
                        2022     176
                        2023     256
                        2024     578
                        2025     154
                        2026       7
Riverside County        2021      84
                        2022    1762
                        2023    1041
                        2024    1648
                        2025     534
                        2026      69
Sacramento County       2021      44
                        2022    1026
                        2023    1613
                        2024    3410
                        2025     714
                        2026      62
San Benito County       2022       1
                        2024       3
                        2025       3
                        2026       1
San Bernardino County   2021       4
                        2022     296
                        2023     321
                        2024     341
                        2025     441
                        2026     160
San Diego County        2021      21
                        2022    1452
                        2023    1142
                        2024    1599
                        2025     581
                        2026      57
San Francisco County    2021       3
                        2022      77
                        2023     110
                        2024     132
                        2025      90
                        2026       6
San Joaquin County      2021       2
                        2022      63
                        2023     116
                        2024     320
                        2025      81
                        2026       4
San Luis Obispo County  2022      33
                        2023      42
                        2024      39
                        2025      41
                        2026       3
San Mateo County        2021      32
                        2022     201
                        2023     497
                        2024     839
                        2025     315
                        2026      28
Santa Barbara County    2022      24
                        2023      42
                        2024      24
                        2025      51
                        2026       3
Santa Clara County      2021      14
                        2022     325
                        2023     753
                        2024    1540
                        2025    1045
                        2026      62
Santa Cruz County       2021       1
                        2022      35
                        2023     182
                        2024     183
                        2025      50
                        2026       3
Shasta County           2022      47
                        2023      61
                        2024      89
                        2025       2
                        2026       3
Siskiyou County         2024       2
                        2025       6
                        2026       5
Solano County           2021      20
                        2022     352
                        2023     350
                        2024     643
                        2025     160
                        2026      14
Sonoma County           2021      27
                        2022     253
                        2023     313
                        2024     555
                        2025     158
                        2026       4
Stanislaus County       2021       6
                        2022     168
                        2023     260
                        2024     358
                        2025     123
Sutter County           2021       1
                        2022      17
                        2023       6
                        2024      19
                        2025       9
Tehama County           2022      13
                        2023      19
                        2024      24
                        2025       2
Trinity County          2023       1
                        2025       6
                        2026       2
Tulare County           2022      19
                        2023      29
                        2024      67
                        2025      14
                        2026       5
Tuolumne County         2022       3
                        2023       2
                        2024       5
                        2025       5
Ventura County          2021       6
                        2022     165
                        2023     134
                        2024     143
                        2025      79
                        2026      18
Yolo County             2021       5
                        2022     197
                        2023     151
                        2024     300
                        2025      78
                        2026       2
Yuba County             2021       1
                        2022      11
                        2023       7
                        2024      19
                        2025       3
Name: Product Type, dtype: int64

In [28]:
#number of counties

heatpump_df['Customer County'].nunique()

54

In [44]:
#get just the years with the highest counts of HPWHs to see if even the highest amount is significant compared to city size
counts = heatpump_df.groupby(['Customer County', 'Year'])['Product Type'].count().reset_index(name='count')
highest_per_county = (counts.sort_values(by='count', ascending = False).groupby('Customer County').first().reset_index())
highest_per_county

#sort in descending order of counts of HPWH
highest_per_county.sort_values(by = 'count', ascending = False)

           Customer County  Year  count
29       Sacramento County  2024   3410
28        Riverside County  2022   1762
17      Los Angeles County  2025   1735
32        San Diego County  2024   1599
38      Santa Clara County  2024   1540
0           Alameda County  2024   1204
26           Orange County  2024    890
36        San Mateo County  2024    839
6      Contra Costa County  2024    837
9            Fresno County  2024    692
42           Solano County  2024    643
27           Placer County  2024    578
43           Sonoma County  2024    555
13             Kern County  2025    464
31   San Bernardino County  2025    441
19            Marin County  2024    394
44       Stanislaus County  2024    358
34      San Joaquin County  2024    320
51             Yolo County  2024    300
12         Imperial County  2025    213
39       Santa Cruz County  2024    183
50          Ventura County  2022    165
33    San Francisco County  2024    132
24             Napa County  2024    126
23         Monterey County  2025    122
3             Butte County  2024    119
8         El Dorado County  2024    107
40           Shasta County  2024     89
48           Tulare County  2024     67
25           Nevada County  2024     67
22           Merced County  2024     61
37    Santa Barbara County  2025     51
14            Kings County  2024     46
21        Mendocino County  2022     45
35  San Luis Obispo County  2023     42
18           Madera County  2023     41
46           Tehama County  2024     24
11         Humboldt County  2022     22
45           Sutter County  2024     19
52             Yuba County  2024     19
7         Del Norte County  2025     13
4         Calaveras County  2025      8
10            Glenn County  2024      7
2            Amador County  2022      7
15             Lake County  2024      7
47          Trinity County  2025      6
41         Siskiyou County  2025      6
49         Tuolumne County  2025      5
5            Colusa County  2022      5
30       San Benito County  2025      3
20         Mariposa County  2025      2
16           Lassen County  2024      1
1            Alpine County  2024      1

### Obtain CA County Household Count Data

In [47]:
#note: the following code has been written with the assistance of Google LLM Gemini
#due to storage and API access issues due to network blocks on Datahub, I used a LLM to stream data from Census Table B11001 and compile the results
#source = U.S. Census Bureau, American Community Survey 5-Year Estimates, Table B11001 (Total Households by County, California).
#numbers are from the 2022 five year release dataset

import io
import pandas as pd

# Embedded dataset of CA counties and total households (ACS estimates)
csv_data = """Customer County,Total Households
Alameda,592160
Alpine,508
Amador,15285
Butte,91799
Calaveras,20173
Colusa,7222
Contra Costa,415951
Del Norte,9851
El Dorado,75474
Fresno,318357
Glenn,10352
Humboldt,53511
Imperial,56272
Inyo,7459
Kern,283525
Kings,42371
Lake,26815
Lassen,9410
Los Angeles,3474345
Madera,46908
Marin,107248
Mariposa,7780
Mendocino,34241
Merced,77914
Modoc,3736
Mono,4985
Monterey,131379
Napa,52093
Nevada,42131
Orange,1032393
Placer,154245
Plumas,8875
Riverside,933756
Sacramento,581335
San Benito,20970
San Bernardino,734125
San Diego,1194210
San Francisco,374787
San Joaquin,231505
San Luis Obispo,113426
San Mateo,276228
Santa Barbara,146741
Santa Clara,689626
Santa Cruz,100188
Shasta,71064
Sierra,1484
Siskiyou,18032
Solano,154345
Sonoma,198595
Stanislaus,184347
Sutter,33469
Tehama,24031
Trinity,5437
Tulare,142713
Tuolumne,21568
Ventura,291415
Yolo,78567
Yuba,26960"""

# Load into a pandas DataFrame
ca_households = pd.read_csv(io.StringIO(csv_data))

ca_households

    Customer County  Total Households
0           Alameda            592160
1            Alpine               508
2            Amador             15285
3             Butte             91799
4         Calaveras             20173
5            Colusa              7222
6      Contra Costa            415951
7         Del Norte              9851
8         El Dorado             75474
9            Fresno            318357
10            Glenn             10352
11         Humboldt             53511
12         Imperial             56272
13             Inyo              7459
14             Kern            283525
15            Kings             42371
16             Lake             26815
17           Lassen              9410
18      Los Angeles           3474345
19           Madera             46908
20            Marin            107248
21         Mariposa              7780
22        Mendocino             34241
23           Merced             77914
24            Modoc              3736
25             Mono              4985
26         Monterey            131379
27             Napa             52093
28           Nevada             42131
29           Orange           1032393
30           Placer            154245
31           Plumas              8875
32        Riverside            933756
33       Sacramento            581335
34       San Benito             20970
35   San Bernardino            734125
36        San Diego           1194210
37    San Francisco            374787
38      San Joaquin            231505
39  San Luis Obispo            113426
40        San Mateo            276228
41    Santa Barbara            146741
42      Santa Clara            689626
43       Santa Cruz            100188
44           Shasta             71064
45           Sierra              1484
46         Siskiyou             18032
47           Solano            154345
48           Sonoma            198595
49       Stanislaus            184347
50           Sutter             33469
51           Tehama             24031
52          Trinity              5437
53           Tulare            142713
54         Tuolumne             21568
55          Ventura            291415
56             Yolo             78567
57             Yuba             26960

### Merge Household Counts by County and HPWH Installation Counts by County

In [64]:
#note: taking some liberties with the exact years since this analysis is just to access viability on an approximate scale

#getting rid of the word "County" from the highest_per_county dataset so we can cleanly merge
highest_per_county['Customer County'] = highest_per_county['Customer County'].str.replace(r'\s+County$', '', regex = True)

merged = highest_per_county.merge(ca_households, on = 'Customer County')
merged = merged.rename(columns = {'count':'Count'})
merged

    Customer County  Year  Count  Total Households
0           Alameda  2024   1204            592160
1            Alpine  2024      1               508
2            Amador  2022      7             15285
3             Butte  2024    119             91799
4         Calaveras  2025      8             20173
5            Colusa  2022      5              7222
6      Contra Costa  2024    837            415951
7         Del Norte  2025     13              9851
8         El Dorado  2024    107             75474
9            Fresno  2024    692            318357
10            Glenn  2024      7             10352
11         Humboldt  2022     22             53511
12         Imperial  2025    213             56272
13             Kern  2025    464            283525
14            Kings  2024     46             42371
15             Lake  2024      7             26815
16           Lassen  2024      1              9410
17      Los Angeles  2025   1735           3474345
18           Madera  2023     41             46908
19            Marin  2024    394            107248
20         Mariposa  2025      2              7780
21        Mendocino  2022     45             34241
22           Merced  2024     61             77914
23         Monterey  2025    122            131379
24             Napa  2024    126             52093
25           Nevada  2024     67             42131
26           Orange  2024    890           1032393
27           Placer  2024    578            154245
28        Riverside  2022   1762            933756
29       Sacramento  2024   3410            581335
30       San Benito  2025      3             20970
31   San Bernardino  2025    441            734125
32        San Diego  2024   1599           1194210
33    San Francisco  2024    132            374787
34      San Joaquin  2024    320            231505
35  San Luis Obispo  2023     42            113426
36        San Mateo  2024    839            276228
37    Santa Barbara  2025     51            146741
38      Santa Clara  2024   1540            689626
39       Santa Cruz  2024    183            100188
40           Shasta  2024     89             71064
41         Siskiyou  2025      6             18032
42           Solano  2024    643            154345
43           Sonoma  2024    555            198595
44       Stanislaus  2024    358            184347
45           Sutter  2024     19             33469
46           Tehama  2024     24             24031
47          Trinity  2025      6              5437
48           Tulare  2024     67            142713
49         Tuolumne  2025      5             21568
50          Ventura  2022    165            291415
51             Yolo  2024    300             78567
52             Yuba  2024     19             26960

### Find percentage of households that installed HPWH in each county

In [70]:
merged['HPWH Installation %'] = merged['Count'] / merged['Total Households'] * 100
merged.sort_values(by = 'HPWH Installation %', ascending = False)

    Customer County  Year  Count  Total Households  HPWH Installation %
29       Sacramento  2024   3410            581335             0.586581
42           Solano  2024    643            154345             0.416599
51             Yolo  2024    300             78567             0.381840
12         Imperial  2025    213             56272             0.378519
27           Placer  2024    578            154245             0.374729
19            Marin  2024    394            107248             0.367373
36        San Mateo  2024    839            276228             0.303735
43           Sonoma  2024    555            198595             0.279463
24             Napa  2024    126             52093             0.241875
38      Santa Clara  2024   1540            689626             0.223309
9            Fresno  2024    692            318357             0.217366
0           Alameda  2024   1204            592160             0.203323
6      Contra Costa  2024    837            415951             0.201226
1            Alpine  2024      1               508             0.196850
44       Stanislaus  2024    358            184347             0.194199
28        Riverside  2022   1762            933756             0.188700
39       Santa Cruz  2024    183            100188             0.182657
13             Kern  2025    464            283525             0.163654
25           Nevada  2024     67             42131             0.159028
8         El Dorado  2024    107             75474             0.141771
34      San Joaquin  2024    320            231505             0.138226
32        San Diego  2024   1599           1194210             0.133896
7         Del Norte  2025     13              9851             0.131966
21        Mendocino  2022     45             34241             0.131421
3             Butte  2024    119             91799             0.129631
40           Shasta  2024     89             71064             0.125239
47          Trinity  2025      6              5437             0.110355
14            Kings  2024     46             42371             0.108565
46           Tehama  2024     24             24031             0.099871
23         Monterey  2025    122            131379             0.092861
18           Madera  2023     41             46908             0.087405
26           Orange  2024    890           1032393             0.086207
22           Merced  2024     61             77914             0.078291
52             Yuba  2024     19             26960             0.070475
5            Colusa  2022      5              7222             0.069233
10            Glenn  2024      7             10352             0.067620
31   San Bernardino  2025    441            734125             0.060072
45           Sutter  2024     19             33469             0.056769
50          Ventura  2022    165            291415             0.056620
17      Los Angeles  2025   1735           3474345             0.049937
48           Tulare  2024     67            142713             0.046947
2            Amador  2022      7             15285             0.045797
11         Humboldt  2022     22             53511             0.041113
4         Calaveras  2025      8             20173             0.039657
35  San Luis Obispo  2023     42            113426             0.037029
33    San Francisco  2024    132            374787             0.035220
37    Santa Barbara  2025     51            146741             0.034755
41         Siskiyou  2025      6             18032             0.033274
15             Lake  2024      7             26815             0.026105
20         Mariposa  2025      2              7780             0.025707
49         Tuolumne  2025      5             21568             0.023182
30       San Benito  2025      3             20970             0.014306
16           Lassen  2024      1              9410             0.010627

### Conclusion: Not enough HPWH installation per county

The above analysis shows that there are not enough treated units to conduct a regression